apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-db-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongo-db-storage
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/prime-micron-468004-q9/regions/us-central1/disks/mongo-db-disk
    fsType: ext4